# Generated by Django 5.0.7 on 2024-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_course_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.TextField(max_length=30),
        ),
    ]
