# Generated by Django 5.0.7 on 2024-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_student_batchtime_alter_student_invoiceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(choices=[('doing', 'Doing'), ('complete', 'Complete'), ('break', 'Break'), ('drop', 'Drop')], max_length=50),
        ),
    ]
