# Generated by Django 5.0.7 on 2024-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.TextField(max_length=5),
        ),
    ]
