# Generated by Django 5.0.7 on 2024-07-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_course_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.TextField(max_length=5)),
                ('SelectDate', models.DateField(max_length=10)),
                ('EnterClassReport', models.TextField(max_length=100)),
                ('Course_SelectSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.course')),
            ],
        ),
    ]
