# Generated by Django 5.0.7 on 2024-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='InvoiceNo',
            field=models.CharField(max_length=5),
        ),
    ]
