# Generated by Django 5.0.7 on 2024-07-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_report_invoiceno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='InvoiceNo',
            new_name='Invoiceno',
        ),
    ]
