# Generated by Django 5.0.7 on 2024-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_invoiceno_report_invoiceno'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoiceno', models.CharField(max_length=5)),
                ('fees', models.CharField(max_length=5)),
                ('duedate', models.CharField(max_length=5)),
            ],
        ),
    ]
