# Generated by Django 5.0.7 on 2024-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='duedate',
            field=models.DateField(max_length=5),
        ),
    ]
