# Generated by Django 5.0.7 on 2024-07-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_fees_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoiceno', models.CharField(max_length=5)),
                ('date', models.DateField(max_length=5)),
                ('time', models.TimeField(max_length=5)),
                ('Course_SelectSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.course')),
            ],
        ),
    ]
